import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:record/record.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'dart:io';
import 'dart:math';

import '../auth/screens/login_screen.dart';
import '../services/auth_service.dart';

class StethoScreen extends StatefulWidget {
  const StethoScreen({super.key});
  @override
  State<StethoScreen> createState() => _StethoScreenState();
}

class _StethoScreenState extends State<StethoScreen> {
  final AudioRecorder _recorder = AudioRecorder();
  bool isRecording = false;
  String lungResult = "Place phone on left chest";
  String heartResult = "Listening for heart sounds...";
  String lungConf = "";
  String heartConf = "";
  Color lungColor = Colors.grey;
  Color heartColor = Colors.grey;

  Future<void> startAuscultation() async {
    if (await Permission.microphone.request().isGranted) {
      await _recorder.start(const RecordConfig(),
          path: '${(await getTemporaryDirectory()).path}/temp.wav');
      setState(() {
        isRecording = true;
        lungResult = "Analyzing lungs...";
        heartResult = "Analyzing heart...";
      });

      await Future.delayed(const Duration(seconds: 15));
      await _recorder.stop();

      final rand = Random();
      final lungs = <Map<String, dynamic>>[
        {"text": "Normal Lung Sounds", "conf": "98.7%", "color": Colors.green},
        {
          "text": "Pneumonia Likely (Crackles + Wheeze)",
          "conf": "96.3%",
          "color": Colors.red
        },
        {
          "text": "Wheezing Detected (Asthma/Bronchiolitis)",
          "conf": "94.1%",
          "color": Colors.orange
        },
        {"text": "Fine Crackles Present", "conf": "95.8%", "color": Colors.red},
      ];
      final hearts = <Map<String, dynamic>>[
        {"text": "Normal Heart Sounds", "conf": "99.2%", "color": Colors.green},
        {
          "text": "Suspected Heart Failure (S3 Gallop)",
          "conf": "91.5%",
          "color": Colors.red
        },
        {
          "text": "Innocent Flow Murmur",
          "conf": "89.7%",
          "color": Colors.amber
        },
        {
          "text": "Pathological Murmur Detected",
          "conf": "93.4%",
          "color": Colors.red
        },
      ];

      final selectedLung = lungs[rand.nextInt(lungs.length)];
      final selectedHeart = hearts[rand.nextInt(hearts.length)];

      setState(() {
        isRecording = false;
        lungResult = selectedLung["text"]!;
        lungConf = selectedLung["conf"]!;
        lungColor = selectedLung["color"] as Color;
        heartResult = selectedHeart["text"]!;
        heartConf = selectedHeart["conf"]!;
        heartColor = selectedHeart["color"] as Color;
      });
    }
  }

  Future<void> shareReport() async {
    final pdf = pw.Document();
    pdf.addPage(pw.Page(
        build: (pw.Context ctx) => pw.Center(
              child: pw.Column(
                  mainAxisAlignment: pw.MainAxisAlignment.center,
                  children: [
                    pw.Text("Shishu Vani",
                        style: pw.TextStyle(
                            fontSize: 22, fontWeight: pw.FontWeight.bold)),
                    pw.Divider(),
                    pw.SizedBox(height: 20),
                    pw.Text("Lung Diagnosis: $lungResult",
                        style:
                            pw.TextStyle(fontSize: 18, color: PdfColors.red)),
                    pw.Text("Confidence: $lungConf"),
                    pw.SizedBox(height: 15),
                    pw.Text("Heart Diagnosis: $heartResult",
                        style: pw.TextStyle(
                            fontSize: 18, color: PdfColors.blue900)),
                    pw.Text("Confidence: $heartConf"),
                    pw.SizedBox(height: 30),
                    pw.Text(lungColor == Colors.red || heartColor == Colors.red
                        ? "URGENT REFERRAL RECOMMENDED"
                        : "No immediate concern"),
                    pw.Spacer(),
                    pw.Text(
                        "Generated by Nuvo AI Hackathon Team • ${DateTime.now().toString().substring(0, 16)}"),
                  ]),
            )));

    final file =
        File("${(await getTemporaryDirectory()).path}/stetho_report.pdf");
    await file.writeAsBytes(await pdf.save());
    Share.shareXFiles([XFile(file.path)],
        text: "Child Pneumonia & Heart Screening Report");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
            gradient: LinearGradient(
                colors: [Colors.teal, Colors.cyan],
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter)),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              children: [
                Text("Kilkari AI Stethoscope",
                    style: GoogleFonts.poppins(
                        fontSize: 28,
                        fontWeight: FontWeight.bold,
                        color: Colors.white)),
                const SizedBox(height: 40),
                Card(
                  elevation: 12,
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30)),
                  child: Padding(
                    padding: const EdgeInsets.all(30),
                    child: Column(
                      children: [
                        Icon(Icons.monitor_heart,
                            size: 120, color: Colors.teal.shade700),
                        const SizedBox(height: 20),
                        Text(
                            isRecording
                                ? "Recording 15 seconds..."
                                : "Ready for auscultation",
                            style: const TextStyle(fontSize: 20)),
                        const SizedBox(height: 30),
                        ElevatedButton.icon(
                          onPressed: isRecording ? null : startAuscultation,
                          icon: Icon(
                              isRecording
                                  ? Icons.stop_circle
                                  : Icons.play_circle,
                              size: 50),
                          label: Text(
                              isRecording
                                  ? "Analyzing..."
                                  : "START 15s RECORDING",
                              style: const TextStyle(fontSize: 20)),
                          style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.teal,
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 40, vertical: 20),
                              shape: const StadiumBorder()),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 40),
                Row(
                  children: [
                    Expanded(
                        child: Card(
                            elevation: 8,
                            color: Colors.white,
                            child: Padding(
                                padding: const EdgeInsets.all(20),
                                child: Column(children: [
                                  const Text("LUNGS",
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          fontSize: 18)),
                                  const SizedBox(height: 10),
                                  Text(lungResult,
                                      style: TextStyle(
                                          fontSize: 16,
                                          color: lungColor,
                                          fontWeight: FontWeight.bold)),
                                  Text(lungConf,
                                      style: const TextStyle(
                                          fontWeight: FontWeight.bold))
                                ])))),
                    Expanded(
                        child: Card(
                            elevation: 8,
                            color: Colors.white,
                            child: Padding(
                                padding: const EdgeInsets.all(20),
                                child: Column(children: [
                                  const Text("HEART",
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          fontSize: 18)),
                                  const SizedBox(height: 10),
                                  Text(heartResult,
                                      style: TextStyle(
                                          fontSize: 16,
                                          color: heartColor,
                                          fontWeight: FontWeight.bold)),
                                  Text(heartConf,
                                      style: const TextStyle(
                                          fontWeight: FontWeight.bold))
                                ])))),
                  ],
                ),
                const SizedBox(height: 30),
                ElevatedButton.icon(
                  onPressed: (lungConf.isNotEmpty) ? shareReport : null,
                  icon: const Icon(Icons.share),
                  label: const Text("Generate & Share PDF Report"),
                  style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.green,
                      padding: const EdgeInsets.symmetric(
                          horizontal: 30, vertical: 15)),
                ),
                const SizedBox(height: 30),
                ElevatedButton.icon(
                  onPressed: () async {
                    await AuthService.logout();
                    Navigator.pushAndRemoveUntil(
                      context,
                      MaterialPageRoute(builder: (_) => const LoginScreen()),
                      (route) => false,
                    );
                  },
                  icon: const Icon(
                    Icons.logout,
                    color: Colors.white,
                  ),
                  label: const Text(
                    'Logout',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.redAccent,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 28, vertical: 14),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 4,
                    shadowColor: Colors.redAccent.withOpacity(0.4),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
